### ISSUE TITLE
Use InternalVisibleTo

### ISSUE THREAD

**Issue by mpostol** [MichalDudkiewicz/TPUM#4]
<https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=net-6.0>

**Comment by MichalDudkiewicz** [comment]
Applied. Please see the following commit for the diff:
[7f71ce2](https://github.com/MichalDudkiewicz/TPUM/commit/7f71ce23d38121986540849756a36ad493715961)

**Comment by mpostol** [comment]
As a rule, let close the issue by the reporter to make sure that the result is as expected. Now the solution looks OK.
